"""Tester Agent — graph-aware test generation for the V2 multi-agent pipeline.

Exposes:
  - _LLMTestOutput  Pydantic model (test_code) — schema for LLM structured output
  - TestResult      Pydantic model (test_code, test_file_path, framework)
  - test(question, G, target_node_id, repo_root=None, settings=None) -> TestResult

Algorithm:
  1. Detect test framework by scanning repo_root for marker files (no LLM call).
  2. Enumerate callee mock targets from CALLS-edge successors of target_node_id.
  3. Call LLM with with_structured_output(_LLMTestOutput) to obtain test_code only.
  4. Assemble TestResult with test_file_path derived deterministically from
     (target_name, framework) — never generated by the LLM.

Critical: get_llm() and get_settings() are imported INSIDE test() body —
never at module level. This prevents ValidationError during pytest collection
when API keys are absent.
"""
from __future__ import annotations

from pathlib import Path
from typing import Literal

import networkx as nx
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel


# ---------------------------------------------------------------------------
# Constants — safe at import time (no get_llm() / get_settings() here)
# ---------------------------------------------------------------------------

_FRAMEWORK_MARKERS: dict[str, list[str]] = {
    "pytest":  ["pytest.ini", "conftest.py", "setup.cfg"],
    "jest":    ["jest.config.js", "jest.config.ts", "jest.config.json"],
    "vitest":  ["vitest.config.ts", "vitest.config.js"],
    "junit":   ["pom.xml", "build.gradle"],
}

_MOCK_SYNTAX: dict[str, str] = {
    "pytest":  "from unittest.mock import patch\n@patch('module.callee')",
    "jest":    "jest.mock('./module');",
    "vitest":  "vi.mock('./module');",
    "junit":   "@Mock\nprivate CalleeClass callee;",
    "unknown": "from unittest.mock import patch\n@patch('module.callee')",
}

TESTER_SYSTEM = """You are a test code generation assistant. \
Given a target function and its callees (dependencies), generate runnable test code.

Framework: {framework}
Mock syntax for this framework:
{mock_syntax}

REQUIREMENTS:
1. Generate EXACTLY three or more test functions: one for the happy path, \
one for error/exception cases, and one for edge cases (empty input, boundary values, etc.).
2. Every callee listed in "Mock targets" must appear as a mock/patch in the test setup.
3. Use correct {framework} syntax — import statements, test runner decorators, assertions.
4. Return ONLY valid, runnable code. No markdown fences. No explanatory text.

Mock targets (callees of the target function):
{mock_targets}"""

TESTER_PROMPT = ChatPromptTemplate.from_messages([
    ("system", TESTER_SYSTEM),
    ("human", "Generate tests for: {question}\n\nTarget function: {target_name}\n"
              "File: {target_file}\nLines: {line_start}-{line_end}"),
])


# ---------------------------------------------------------------------------
# Pydantic output models
# ---------------------------------------------------------------------------

class _LLMTestOutput(BaseModel):
    """Schema for the LLM structured output call — test code only."""

    test_code: str


class TestResult(BaseModel):
    """Complete test generation result returned by test()."""

    test_code: str
    test_file_path: str  # derived deterministically, not by LLM
    framework: str       # detected deterministically, not by LLM


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _detect_framework(repo_root: str) -> str:
    """Detect the test framework by scanning repo_root for marker files.

    Priority order: pytest → jest → vitest → junit.
    Fallback: if any test_*.py files exist, return 'pytest'.
    Final fallback: return 'unknown'.
    """
    root = Path(repo_root)
    for framework, markers in _FRAMEWORK_MARKERS.items():
        if any((root / marker).exists() for marker in markers):
            return framework
    if any(root.rglob("test_*.py")):
        return "pytest"
    return "unknown"


def _get_callees(G: nx.DiGraph, target_id: str) -> list[dict]:
    """Return list of callee dicts for all CALLS-edge successors of target_id.

    Each dict has keys 'name' and 'file_path'.
    Raises ValueError if target_id is not in G.
    """
    if target_id not in G:
        raise ValueError(f"target_node_id {target_id!r} not found in graph")
    callees = []
    for succ in G.successors(target_id):
        if G.edges[target_id, succ].get("type") == "CALLS":
            callees.append({
                "name": G.nodes[succ].get("name", succ),
                "file_path": G.nodes[succ].get("file_path", ""),
            })
    return callees


def _derive_test_path(func_name: str, framework: str) -> str:
    """Derive a conventional test file path from func_name and framework.

    Normalises dots and double-colons in func_name to underscores.
    """
    name = func_name.replace(".", "_").replace("::", "_")
    if framework == "jest":
        return f"__tests__/{name}.test.ts"
    if framework == "vitest":
        return f"{name}.test.ts"
    if framework == "junit":
        return f"src/test/java/{name.capitalize()}Test.java"
    # pytest (default / unknown)
    return f"tests/test_{name}.py"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def test(
    question: str,
    G: nx.DiGraph,
    target_node_id: str,
    repo_root: str | None = None,
    settings=None,
) -> TestResult:
    """Detect framework, enumerate mock targets, generate tests via LLM, return TestResult.

    Args:
        question: Natural-language description of what to test.
        G: Project call graph (NetworkX DiGraph with CALLS-typed edges).
        target_node_id: The function under test (must exist in G).
        repo_root: Path to the repository root for framework detection; defaults to '.'.
        settings: Optional Settings instance; lazy-loaded from app.config if None.

    Returns:
        TestResult with test_code (from LLM), test_file_path and framework
        (both derived deterministically — never from LLM output).
    """
    # Step 1 — Settings lazy import (CRITICAL: inside function body)
    if settings is None:
        from app.config import get_settings  # noqa: PLC0415
        settings = get_settings()

    # Step 2 — Framework detection
    resolved_root = repo_root if repo_root is not None else "."
    framework = _detect_framework(resolved_root)

    # Step 3 — Callee enumeration (mock targets)
    callees = _get_callees(G, target_node_id)
    if callees:
        mock_targets = "\n".join(
            f"  - {c['name']} (from {c['file_path']})" for c in callees
        )
    else:
        mock_targets = "(none — target has no external dependencies)"

    # Step 4 — Target node attributes
    if target_node_id not in G:
        raise ValueError(f"target_node_id {target_node_id!r} not found in graph")
    attrs = G.nodes[target_node_id]
    target_name = attrs.get("name", target_node_id)
    target_file = attrs.get("file_path", "")
    line_start = attrs.get("line_start", 0)
    line_end = attrs.get("line_end", 0)

    # Step 5 — LLM call with structured output (lazy import — CRITICAL: inside function body)
    from app.core.model_factory import get_llm  # noqa: PLC0415
    llm = get_llm()
    structured_llm = llm.with_structured_output(_LLMTestOutput)
    prompt = TESTER_PROMPT.partial(
        framework=framework,
        mock_syntax=_MOCK_SYNTAX.get(framework, _MOCK_SYNTAX["unknown"]),
        mock_targets=mock_targets,
    )
    chain = prompt | structured_llm
    llm_output: _LLMTestOutput = chain.invoke({
        "question": question,
        "target_name": target_name,
        "target_file": target_file,
        "line_start": line_start,
        "line_end": line_end,
    })

    # Step 6 — Assemble TestResult deterministically (never trust LLM for path or framework)
    test_file_path = _derive_test_path(target_name, framework)
    return TestResult(
        test_code=llm_output.test_code,
        test_file_path=test_file_path,
        framework=framework,
    )
